/**
 *TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/04/2016
 */
/**
 * Creates a instance of AuthenticationResponse
 *
 * @constructor
 */

angular.module('TelstraSMSAUSLib').factory('AuthenticationResponse',function(BaseModel){
	var AuthenticationResponse = function(obj) {
		if(!obj){
						this.accessToken = null;     
    				this.expiresIn = null;     
    								//Append to variable dictionary
    this._variableDict['accessToken'] = 'access_token';
    this._variableDict['expiresIn'] = 'expires_in';
    					
		}
		else
		{
					this.accessToken = obj.access_token;
    		this.expiresIn = obj.expires_in;
    //Append to variable dictionary
    this._variableDict['accessToken'] = 'access_token';
    this._variableDict['expiresIn'] = 'expires_in';
 
		}
	}

	AuthenticationResponse.prototype = new BaseModel();
	AuthenticationResponse.prototype.constructor = AuthenticationResponse;

		/**
	 * TODO: Write general description for this method
	 *
	 * @return {string}
	 */
	AuthenticationResponse.prototype.getAccessToken = function() {
		return this.accessToken;
	};

	/**
	 * Setter for AccessToken
	 * 
	 * @param {string} value 
	 */
	AuthenticationResponse.prototype.setAccessToken = function(value) {
		this.accessToken = value;
	};

		/**
	 * TODO: Write general description for this method
	 *
	 * @return {string}
	 */
	AuthenticationResponse.prototype.getExpiresIn = function() {
		return this.expiresIn;
	};

	/**
	 * Setter for ExpiresIn
	 * 
	 * @param {string} value 
	 */
	AuthenticationResponse.prototype.setExpiresIn = function(value) {
		this.expiresIn = value;
	};

	
	return AuthenticationResponse;
});