/**
  *TelstraSMSAUSLib
  *
  *This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/04/2016
  */


angular.module('TelstraSMSAUSLib').factory('ResponseStatusEnum', function() {
    return {

        //The message is pending and has not yet been sent to the intended recipient    
        PEND : "PEND",

        //The message has been sent to the intended recipient, but has not been delivered yet    
        SENT : "SENT",

        //The message has been delivered to the intended recipient    
        DELIVRD : "DELIVRD",

        //The message has been read by intended recipient and the recipient's response has been received    
        READ : "READ",
    };
});