/**
 *TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/04/2016
 */
/**
 * Creates a instance of SendMessageRequest
 *
 * @constructor
 */

angular.module('TelstraSMSAUSLib').factory('SendMessageRequest',function(BaseModel){
	var SendMessageRequest = function(obj) {
		if(!obj){
						this.to = null;     
    				this.body = null;     
    													
		}
		else
		{
					this.to = obj.to;
    		this.body = obj.body;
 
		}
	}

	SendMessageRequest.prototype = new BaseModel();
	SendMessageRequest.prototype.constructor = SendMessageRequest;

		/**
	 * TODO: Write general description for this method
	 *
	 * @return {string}
	 */
	SendMessageRequest.prototype.getTo = function() {
		return this.to;
	};

	/**
	 * Setter for To
	 * 
	 * @param {string} value 
	 */
	SendMessageRequest.prototype.setTo = function(value) {
		this.to = value;
	};

		/**
	 * TODO: Write general description for this method
	 *
	 * @return {string}
	 */
	SendMessageRequest.prototype.getBody = function() {
		return this.body;
	};

	/**
	 * Setter for Body
	 * 
	 * @param {string} value 
	 */
	SendMessageRequest.prototype.setBody = function(value) {
		this.body = value;
	};

	
	return SendMessageRequest;
});