/**
 *TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/04/2016
 */

'use strict';
angular.module('TelstraSMSAUSLib',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : "https://api.telstra.com/v1",

        //The OAuth 2.0 access token to be set before API calls
        //TODO: Replace the oAuthAccessToken with an appropriate value
        oAuthAccessToken : "TODO: Replace"

    };
});

